pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        REPO_NAME = "todo-app"
        ACCOUNT_ID = "386082432619"  // Replace with your AWS account ID
        IMAGE_TAG = "latest"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir() // ensures no leftover files from previous builds
            }
        }

        stage('Checkout Code') {
            steps {
                // Use Git plugin to fetch the repo
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/muhab404/todo']]
                ])
            }
        }

        stage('Test Docker') {
            steps {
                sh 'docker ps'
            }
        }


        stage('Login to AWS ECR') {
            steps {
                withAWS(credentials: 'aws-creds', region: "${AWS_REGION}") {
                    sh '''
                    aws ecr get-login-password --region $AWS_REGION | \
                        docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $REPO_NAME:$IMAGE_TAG .
                '''
            }
        }

        stage('Tag Docker Image') {
            steps {
                sh '''
                docker tag $REPO_NAME:$IMAGE_TAG \
                    $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
                '''
            }
        }

        stage('Push Docker Image to ECR') {
            steps {
                sh '''
                docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
                '''
            }
        }
    }

    post {
        success {
            echo "Docker image pushed to ECR successfully!"
        }
        failure {
            echo "Pipeline failed! Check logs."
        }
    }
}
